### ISSUE TITLE
is this it?

### ISSUE THREAD

**Issue by luh-99** [Itay2805/fx991es-hacking#1]
https://www.walmart.com/ip/FX-991ES-PLUS-Calculator-417-Functions-High-School-University-Calculation-Tool-Computer-Office-Two-Ways-Power-Graphing/2145542152?athcpid=2145542152&athpgid=AthenaItempage&athcgid=null&athznid=si&athieid=v0_eeMTYuMCw0OTEuNDQsMC4wMjQ2NTYyNTE3NTg2OTU4MywwLjVf&athstid=CS055%7ECS004&athguid=210CaJarZQebeJY7YuhLZGl2BswBWmPRcOFx&athancid=111261111&athposb=0&athena=true&sid=8c52f872-2e41-40f1-ada1-2b51edcbf36b

**Comment by Itay2805** [comment]
Yeah, looks like it
